# Generated by Django 5.0.1 on 2024-02-10 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiEngineerTask', '0003_remove_stockmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
